[settings]
env_shell_expand = true

[tools]
node = "latest"

[env]
GITHUB_TOKEN = { value = "${GITHUB_TOKEN:-}", redact = true }
APP_STORE_MOCK = true
PORT = "3000"

[tasks.build-library]
description = "Build the library"
run = "npm --workspace='tildagon-app' run build"

[tasks.build-website]
description = "Build the website"
depends = ["build-library"]
run = "npm --workspace='tildagon-app-directory-site' run build"

[tasks.dev]
description = "Serve the website"
depends = ["build-library"]
run = "npm --workspace='tildagon-app-directory-site' run dev"
