title: App
description: Represents an application in the Tildagon App Store.
type: object
properties:
  code:
    type: string
  id:
    $ref: "./AppId.yaml"
  releaseTime:
    type: string
    format: date-time
  tarballUrl:
    type: string
    format: uri
  manifest:
    $ref: "./AppManifest.yaml"
required:
  - code
  - id
  - releaseTime
  - tarballUrl
  - manifest
